services:

  builder:
    build:
      context: .
      dockerfile: ../builder.Dockerfile
    image: builder

  node:
    build:
      context: .
      dockerfile: ../node.Dockerfile
    image: node
    depends_on:
      - builder

  cardano-node-bp-mainnet:
    build: 
      context: .
      dockerfile: mainnet.Dockerfile
    image: cardano-node-bp-mainnet
    container_name: cardano-node-bp-mainnet
    ports:
      - 6000:6000 # Cardano node relay port
      - 12798:12798 # Cardano node metrics
    volumes:
      - ./node/db/:/node/db
      - ./node/ipc/:/node/ipc
      - ./node/logs/:/node/logs
      - ./node/pool-keys:/node/pool-keys
      - ./node/data:/node/data
    depends_on:
      - node

  node-exporter-mainnet: # Listening by default on port 9100
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter-mainnet
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    depends_on:
      - cardano-node-bp-mainnet