services:

  cardano-node-bp-sanchonet:
    build: .
    image: cardano-node-bp-sanchonet
    container_name: cardano-node-bp-sanchonet
    ports:
      - 6004:6004 # Cardano node relay port
      - 12794:12798 # Cardano node metrics
    volumes:
      - ./node/db/:/node/db
      - ./node/ipc/:/node/ipc
      - ./node/logs/:/node/logs
      - ./node/pool-keys:/node/pool-keys
      - ./node/data:/node/data
      
  node-exporter-sanchonet: # Listening by default on port 9100
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter-sanchonet
    ports:
      - 9104:9100
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    depends_on:
      - cardano-node-bp-sanchonet
