services:

  cardano-node-bp-preprod:
    build: .
    image: cardano-node-bp-preprod
    container_name: cardano-node-bp-preprod
    ports:
      - 6001:6001 # Cardano node relay port
      - 12791:12791 # Cardano node metrics
    volumes:
      - ./node/db/:/node/db
      - ./node/ipc/:/node/ipc
      - ./node/logs/:/node/logs
      - ./node/pool-keys:/node/pool-keys
      - ./node/data:/node/data

  node-exporter-preprod: # Listening by default on port 9100
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter-preprod
    ports:
      - 9101:9101
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    depends_on:
      - cardano-node-bp-preprod